import os

BOT_TOKEN = os.getenv('DISCORD_BOT_TOKEN')
CHAINBASE_API_URL = os.getenv('BASE_URL')
CHAINBASE_API_KEY = os.getenv('CHAINBASE_API_KEY')
API_TIME_LIMIT = 20
MAX_COLUMN_SHOW = 4
MAX_TABLE_SHOW = 2
MAX_ROW_SHOW = 20
